export const defaultLoginProps = {
  employeeID: '',
  password: '',
};

export const defaultCreateUserProps = {
  employeeId:'',
  userId: '',
  userName: '',
  phoneNumber: '',
  email: '',
  location: '',
  address: '',
  password: '',
  profileImage: '',
  joiningDate: '',
  previousCompany: '',
  experienceYears: null, 
  experienceMonths: null,
  role:'',
  otpPageView: false,
  employeeView: false,
  employeeAdd: false,
  employeeEdit: false,
  employeeDelete: false,
  leadsView: false,
  leadsAdd: false,
  leadsEdit: false,
  leadsDelete: false,
  developerView: false,
  developerAdd: false,
  developerEdit: false,
  developerDelete: false,

};
